### ISSUE TITLE
couchdb crash/restart cycle

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/buda-base#1]
The following snippet from /var/log/daemon.log illustrates a repeated cycle of couchdb crashing and restarting. It looks like a config file issue:

> gen_server config terminated with reason: no match of right hand value {error,eacces} at config_writer:save_to_file/2(line:38)

[couchdb-crash-restart-cycle.txt](https://github.com/BuddhistDigitalResourceCenter/buda-base/files/842487/couchdb-crash-restart-cycle.txt)

**Comment by eroux** [comment]
I got this problem earlier and fixed by adding:

```
chown -R couchdb:couchdb /opt/couchdb
```

to the couchdb script, I don't understand why it doesn't work on your system... can you execute this command by hand in an ssh shell and tell me what happens?

**Comment by eroux** [comment]
there was indeed an error in the script, fixed now, thanks!

**Comment by manas86** [comment]
@eroux how is this fixed?

**Comment by xristy** [comment]
@manas86 I don't know that the problem is fixed but we have not been doing any couchdb development since almost a year now. couchdb is not now part of the buda platform.
