### ISSUE TITLE
ldsearch issues in buda-base

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/buda-base#4]
It would be best if we have a _release_ of ldsearch as a war file that can be downloaded from github or stashed in buda-base/conf/lds/ perhaps. 

I don't see the benefit of installing mvn and git-core and cloning the ldsearch repo and then mvn which downloads all the dependencies every time the vagrant provisioning is run fresh.

Also unless ldsearch is supposed to be contacted on the same port as fuseki (13180 in the current buda-base) then it would be appropriate to setup a separate tomcat for ldsearch - and other app-server servlets.

**Comment by MarcAgate** [comment]
Hi Chris,
Elie asked me not to put any war in any git directory for the sake of not having huge repositories and also because git is not tailored to handle such compressed files.
I agree it's a pain to download all the dependencies during vagrant provisionning: however, I had no choice but doing so, precisely for generating the war file.
Regarding the tomcat server used for ldsearch, we can certainly have a different tomcat instance. I think the current setup was meant to be temporary.

**Comment by xristy** [comment]
My understanding is a bit different. Please see [about github releases](https://help.github.com/articles/about-releases). In particular,

> With Releases, you can provide links to binary files, as well as release notes describing your changes

and

> We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2 GB in size.

**Comment by MarcAgate** [comment]
Well... There might be a difference in between providing links to binary files in a release and managing changes to these files throughout the project history. I suspect binary files are only generated and published in the repository at release time while being handled locally at dev time. 
Anyway, I don't have any git expertise and therefore I cannot argue. Moreover, I have no preference about the way we should manage this case. We just need to make a decision about this very matter and stick to it.

**Comment by xristy** [comment]
Let's use the github releases feature to make prebuilt war files and jar files available to consumers such as vagrant provisioning. It is clear that github intends releases to be used inthis manner. Once something like lds-pdi is to the point of being available for integration into buda-base then it makes sense to make a release. The release feature provides a way to support workflow steps beyond maven. I'll move the jena-fuseki-3.7.0-SNAPSHOT.war into the bdrc fork of jena as a release. Then the only binary left in the buda-base/conf is lucene-bo-1.1.1.jar and that can be moved to its corresponding releases as well.

**Comment by MarcAgate** [comment]
I think this one has become an old story... don't you think?

**Comment by xristy** [comment]
indeed
